export const seocsList = [
  {
      "id": "AUD_AUDIOLOGY COCHLEAR IMPLANT ANNUAL FOLLOW UP_1.3.2_PRCT",
      "name": "Audiology Cochlear Implant Annual Follow Up",
      "previewText": "VHA Office of Community Care - Standardized Episode of Care\nAudiology Cochlear Implant Annual Follow Up\n\nSEOC ID:AUD_AUDIOLOGY COCHLEAR IMPLANT ANNUAL FOLLOW UP_1.3.2_PRCT\nDescription:This authorization covers services associated with all medical care listed below for the referred condition.\nDuration:120 days\n\nProcedural Overview:\n1. Follow-up for cochlear implant programming\n\n* Additional surgical or medical consultations needed relevant to the patient complaint/condition require VA review and approval.\n* DME, prosthetics and orthotics orders must be submitted to the local VA facility prosthetics department for provision.\n* All routine medications must be faxed/sent to the VA to be dispensed by the VA *Urgent/emergent prescriptions can be provided for a 14-day supply only.\n*The Veteran will be required to pay out of pocket for any urgent/emergent medications and can submit a reimbursement request to their local VA facility.",
      "ccConsultName": "COMMUNITY CARE- AUDIOLOGY",
  },
  {
      "id": "AUD_AUDIOLOGY COCHLEAR IMPLANT SURGERY AND FOLLOW UP PRCT_1.2.2_PRCT",
      "name": "Audiology Cochlear Implant Surgery and Follow Up PRCT",
      "previewText": "VHA Office of Community Care - Standardized Episode of Care\nAudiology Cochlear Implant Surgery and Follow Up PRCT\n\nSEOC ID:AUD_AUDIOLOGY COCHLEAR IMPLANT SURGERY AND FOLLOW UP PRCT_1.2.2_PRCT\nDescription:This authorization covers services associated with all medical care listed below as for the referred condition. This SEOC does not cover osseointegrated hearing aids. Prior to authorization of cochlear implant surgery, cochlear implant candidacy documentation is required to be sent to the VA Centralized Audiology Team (please refer to disclaimer below).\nDuration:365 days\n\nProcedural Overview:\n1. Initial outpatient evaluation and treatment for the referred condition indicated on the consult\n2. Surgical evaluation as clinically indicated for the referred condition on the consult\n3. Immunizations as recommended by CDC\n4. Diagnostic imaging relevant to the referred condition on the consult\n5. Labs and pathology relevant to the referred condition on the consult\n6. Diagnostic studies relevant to the referred condition on the consult\n7. Anesthesia consultation related to the procedure\n8. Pre-operative medical and cardiac clearance as indicated, to include H+P/labs, EKG, CXR\n9. One Cochlear Implant Surgery and hospitalization if required (inpatient admission or observation)\n10. Inpatient admission or observation status for complications related to the procedure       ** VA notification within 72 hours to local Community Care office who initiated the referral is required for complications related to the initial surgery\n11. Follow up visits with the surgeon\n12. Post-op imaging\n13. Post-operative cochlear implant follow up after the surgery with the audiologist for the initial activation and then at a minimum of 1 month, 3 months, 6 months, 9 months and 12 months post-procedure\n\n*Device is included in the billing code. VA will not be providing the device, the community provider is reimbursed through the Medicare code for the devices.\n* DME, prosthetics and orthotics orders must be submitted to the local VA facility prothetics department for provision.\n* Prior to authorization of implant surgery, cochlear implant candidacy documentation would be sent to the VA Centralized Audiology Team. Their phone number is (720) 497-2330 and their email is VACAT@va.gov \n* Additional consultations needed relevant to the patient complaint/condition require VA review and approval.\n* All routine medications must be faxed/sent to the VA to be dispensed by the VA.\n*Urgent/emergent prescriptions can be provided for a 14-day supply only.\n*The Veteran will be required to pay out of pocket for any urgent/emergent medications and can submit a reimbursement request to their local VA facility.",
      "ccConsultName": "COMMUNITY CARE- AUDIOLOGY",
  },
  {
      "id": "AUD_AUDIOLOGY COMPREHENSIVE_1.1.2_PRCT",
      "name": "Audiology Comprehensive",
      "previewText": "VHA Office of Community Care - Standardized Episode of Care\nAudiology Comprehensive\n\nSEOC ID:AUD_AUDIOLOGY COMPREHENSIVE_1.1.2_PRCT\nDescription:This authorization covers services associated with all medical care listed below for the referred condition. Utilization of this SEOC requires previously documented audiologic evaluation/audiogram through the VA or community provider. This SEOC excludes cochlear implant procedures.\nDuration:365 days\n\nProcedural Overview:\n1. Initial outpatient evaluation and treatment for the referred condition indicated on the consult\n2. Device and/or programming follow up as clinically necessary\n3. Diagnostic studies including but not limited to:  evoked potential testing, VNG, posturography, VHIT, VEMP, rotary chair after posturography relevant to the referred condition on the consult\n4. Canalith Repositioning - visit with 2 follow ups**\n5. Surgical evaluation for osseointegrated hearing devices as clinically indicated for the referred condition on the consult\n6. Diagnostic imaging relevant to the evaluation for an osseointegrated hearing device\n7. Labs and pathology relevant to the evaluation for an osseointegrated hearing device **\n8. Anesthesia consultation related to the evaluation for an osseointegrated hearing device\n9. Pre-operative medical and cardiac clearance as indicated, to include H+P/labs, EKG, CXR as related to the evaluation for an osseointegrated hearing device\n10. Inpatient or observation admission for surgical procedure if indicated\n11. Inpatient admission or observation status for complications related to the osseointegrated hearing device.  ** VA notification within 72 hours to local Community Care office who initiated the referral is required for complications related to the initial surgery\n12. Follow-up visits for this episode of care, to include up to three (3) clinically indicated\nvisits after the global period\n13. Follow-up imaging as required by the surgeon after an osseointegrated hearing devices had been implanted\n14. Follow-up studies as required by the surgeon after an osseointegrated hearing devices had been implanted\n15. Audiology fitting of processor when osseointegration is complete as determined by surgeon\n16. Follow up osseointegrated hearing testing after device fitting\n\n* Additional surgical or medical consulations needed, relevant to the patient complaint/condition, require VA review and approval\n* DME, prosthetics and orthotics must be submitted to the local VA facility prosthetics department for provision.\n* All routine medications must be faxed/sent to the VA to be dispensed by the VA.\n* Urgent/emergent prescriptions can be provided for a 14-day supply only.\n* The Veteran will be required to pay out of pocket for any urgent/emergent medications and can submit a reimbursement request to their local VA facility.",
      "ccConsultName": "COMMUNITY CARE- AUDIOLOGY",
  },
  {
      "id": "AUD_AUDIOLOGY DS ROUTINE_1.0.3_PRCT",
      "name": "Audiology DS Routine",
      "previewText": "VHA Office of Community Care - Standardized Episode of Care\nAudiology DS Routine\n\nSEOC ID:AUD_AUDIOLOGY DS ROUTINE_1.0.3_PRCT\nDescription:This authorization covers services associated with all medical care listed below for the referred condition. Prior to authorization of cochlear implant surgery, cochlear implant candidacy documentation is required to be sent to the VA Centralized Audiology Team (please refer to disclaimer below).\nDuration:240 days\n\nProcedural Overview:\n1. Initial outpatient evaluation and treatment for the one (1) comprehensive diagnostic audiologic evaluation for the referred condition indicated on the consult\n2. One hearing aid fitting\n3. Three follow-up visits\n\n** If hearing aids are indicated the community provider is required to send the hearing aid order form and a copy of the Veteran's audiogram to the referring VA for approval and ordering. Hearing aids will be mailed to the community provider by the VA.\n** Prior to authorization of cochlear implant surgery, cochlear implant candidacy documentation would be sent to the VA Centralized Audiology Team. Their phone number is (720) 497-2330 and their email is VACAT@va.gov.\n*Additional consultations needed relevant to the patient complaint/condition require VA review and approval.\n*All routine medications must be faxed/sent to the VA to be dispensed by the VA.\n* Urgent/emergent prescriptions can be provided for a 14-day supply only.\n* The Veteran will be required to pay out of pocket for any urgent/emergent medications and can submit a reimbursement request to their local VA facility.",
      "ccConsultName": "COMMUNITY CARE- AUDIOLOGY",
  },
];
